### PR TITLE
Added support for zeus

### PR DESCRIPTION
**Pull request by ricbrue**

### CODE REVIEW

**Comment by jackmitch** [comment]
I've created a zeus branch for you to pull into to, is this working, or just an initial start? I can't see how the numpy settings would be passed with such an old numpy version?

**Comment by ricbrue** [comment]
Let's consider just an initial start, I'm working with the numpy version 1.17, python 3.7 and it managed to compile using the meta-scipy for zeus (1.3.3). I've successfully tested few things on the deployed image and it seems to work.

**Comment by jackmitch** [comment]
Great, in this case I would assume it's an arm64 based image then?

**Comment by ricbrue** [comment]
Exactly, working on Variscite SOM, [here](https://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_ZEUS_V3.0_DART-MX8M-PLUS) the wiki details of the BSP if you need further info. As you can see, unfortunately, they are not releasing Yocto versions greater than zeus for such SOM so far, so I have to fit your meta layer into my project.

**Comment by jackmitch** [comment]
Ok, so in this case then you get away without the extra numpy configuration as the issues arise when it's a 64bit build host and a 32bit target, so I would be happy to merge this in if you make a couple of tweaks to the README, gatesgarth->zeus, and put a note somewhere that it's only arm64 tested.

**Comment by jackmitch** [comment]
https://github.com/tuxable-ltd/meta-scikit-learn/commit/01d6157f8a685bff89bffc4e3ffefe34b91ce291

**Comment by jackmitch** [comment]
Excellent, thanks!

**Pull request merged**
